"""`select_env` — domain-agnostic replacement for the reference repo's helper.

The reference `select_env(dev=None, staging=None, prod=None, default=None)`
had the three environment names baked into its signature and also silently
used `dev` as `//conditions:default` when no explicit default was given.
Both decisions leak policy into the ruleset. This implementation:

  * Takes the mapping as a single `dict[str, Any]` so the helper is neutral
    about which environments exist.
  * Requires an explicit `default` (or omits the default branch entirely).
  * Accepts a `flag_package` so callers specify where their
    `coen_applied_lifecycle_environments()` invocation lives; there is no
    `//build_flags:...` hardcode anywhere.
"""

_NO_DEFAULT = struct(sentinel = "no-default")

def select_env(mapping, default = _NO_DEFAULT, flag_package = None):
    """Build a `select()` keyed on the lifecycle environment config_settings.

    Args:
      mapping: `dict[str, Any]`. Keys are environment names; values are what
        each env should select to. Any value type accepted by `select()` is
        allowed (list, string, label, etc.).
      default: Value used for `//conditions:default`. When omitted, no
        default branch is emitted and the select() will fail hard for
        environments not in `mapping` — an explicit-is-better-than-implicit
        stance compared to the reference.
      flag_package: `str`. The Bazel package (e.g. `"//deploy/flags"`)
        holding the config_setting targets generated by
        `coen_applied_lifecycle_environments`. Required.

    Returns:
      A `select(...)` expression suitable for use in any rule attribute.
    """
    if flag_package == None:
        fail(
            "select_env(flag_package=...) is required. Pass the package " +
            "where coen_applied_lifecycle_environments(...) was instantiated, " +
            "e.g. '//deploy/flags'.",
        )
    if type(mapping) != "dict":
        fail("select_env: `mapping` must be a dict[str, Any], got %s." % type(mapping))
    if not mapping:
        fail("select_env: `mapping` must be non-empty.")

    pkg = flag_package.rstrip("/")
    out = {}
    for env, value in mapping.items():
        if type(env) != "string" or not env:
            fail("select_env: environment keys must be non-empty strings.")
        out["%s:%s" % (pkg, env)] = value

    if default != _NO_DEFAULT:
        out["//conditions:default"] = default

    return select(out)
