#!/usr/bin/env sh
# Generated by rules_farakov_lifecycle's _release_group. Do not edit the
# template in place; edit release_group.sh.tpl in the ruleset instead.
#
# Invocation contract:
#   $0 [-- <extra args forwarded to every push>]
#
# Each push target below is a `bazel run`-able binary (typically
# rules_oci's oci_push). Extra args after `--` are forwarded verbatim so
# users can, for instance, pass `--insecure` to every push in one shot.
set -eu

EXTRA_ARGS=""
if [ "${1:-}" = "--" ]; then
    shift
    EXTRA_ARGS="$*"
fi

failed_components=""

%{PUSH_INVOCATIONS}

if [ -n "$failed_components" ]; then
    printf 'release_group: failed components:%s\n' "$failed_components" >&2
    exit 1
fi
